
services:
  db:
    image: postgres:latest
    container_name: ecopulse
    environment:
      POSTGRES_DB: ecopulse_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5434:5432"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

