server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecopulse
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    baseline-on-migrate: true
spring-doc:
  paths-to-match: /api/**/v1/**
  swagger-ui:
    use-root-path: true